export type {
  SchedulerEvent,
  SingleEvent,
  RepeatingEvent,
  RepetitionMode,
  EventInstance,
  SoleEventInstance,
  PersistedRepeatedEventInstance,
  VirtualRepeatedEventInstance,
  ScheduleItem,
} from './model/types';

export type {
  GetEventInstanceDetailsResponseDto,
  DetailedEventInstanceDto,
  SoleEventInstanceDetailedDto,
  PersistedRepeatedEventInstanceDetailedDto,
  VirtualRepeatedEventInstanceDetailedDto,
  CancelRepeatingEventAfterTimestampInputDto,
  CreateClassroomEventResponseDto,
  CreateSingleEventResponseDto,
  CreateRepeatingEventResponseDto,
} from 'common.api';

export {
  mapEventInstanceToScheduleItem,
  mapScheduleResponseToScheduleItems,
} from './model/adapters';

export {
  buildOccurrenceCancellationParams,
  type OccurrenceCancelApiTarget,
} from './model/occurrenceCancel';

export {
  getTutorClassroomSchedule,
  getStudentClassroomSchedule,
  getTutorSchedule,
  getStudentSchedule,
  getTutorEventInstanceDetails,
  getStudentEventInstanceDetails,
  getTutorRepeatedEventInstanceDetails,
  getStudentRepeatedEventInstanceDetails,
  rescheduleRepeatedVirtualInstance,
  rescheduleSoleEventInstance,
  createClassroomEvent,
  updateClassroomEvent,
  deleteClassroomEvent,
  cancelEventInstance,
  uncancelEventInstance,
  cancelRepeatedVirtualInstance,
  cancelRepeatingEventAfterTimestamp,
  schedulerQueryKeys,
  useClassroomSchedule,
  useTutorClassroomSchedule,
  useStudentClassroomSchedule,
  useTutorSchedule,
  useStudentSchedule,
  useTutorEventInstanceDetails,
  useStudentEventInstanceDetails,
  useTutorRepeatedEventInstanceDetails,
  useStudentRepeatedEventInstanceDetails,
  useRescheduleRepeatedVirtualInstance,
  useRescheduleSoleEventInstance,
  createLastRepetitionMode,
  useCreateLastRepetitionMode,
  useCreateClassroomEvent,
  useUpdateClassroomEvent,
  useDeleteClassroomEvent,
  useCancelEventInstance,
  useUncancelEventInstance,
  useCancelRepeatedVirtualInstance,
  useCancelRepeatingEventAfterTimestamp,
  type GetClassroomScheduleParams,
  type GetGlobalScheduleParams,
  type UseClassroomScheduleParams,
  type UseGlobalScheduleParams,
  type UseEventInstanceDetailsParams,
  type UseRepeatedEventInstanceDetailsParams,
  type GetEventInstanceDetailsParams,
  type GetRepeatedEventInstanceDetailsParams,
  type CreateClassroomEventParams,
  type UpdateClassroomEventParams,
  type DeleteClassroomEventParams,
  type CancelEventInstanceParams,
  type UncancelEventInstanceParams,
  type CancelRepeatedVirtualInstanceParams,
  type CancelRepeatingEventAfterTimestampParams,
  type RescheduleRepeatedVirtualInstanceParams,
  type RescheduleSoleEventInstanceParams,
  type CreateLastRepetitionModeParams,
} from './model/queries';
