# Основная документация: https://github.com/dorny/paths-filter (см. всё к полю `filters`)

# Пути прописываются в виде picomatch-паттернов:
#   https://github.com/micromatch/picomatch#basic-globbing

# Можно использовать все фишки YAML-я:
# https://ru.wikipedia.org/wiki/YAML#%D0%A1%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%81

# Имена последних объектов (xi_web_files, lintable_files) лучше не менять

config_files: &config_files # изменения тут обязательно запускают все пайплайны
  - '.github/workflows/*'
  - 'package.json'
  - 'package-lock.json'
  - 'turbo.json'
  - '.npmrc'

app_common_files: &app_common_files # тригерят все билда (и депой в main-ветке)
  - *config_files
  - 'packages/**'

xi_web_files: # запускает билд и депой для xi.web
  - *app_common_files
  - 'apps/xi.web/**'
