import { ClassroomPropsT } from './types';

export const classroomsMock: ClassroomPropsT[] = [
  {
    id: 1,
    name: 'Анна Смирнова',
    status: 'active',
    kind: 'individual',
    description: 'Подготовка к ЕГЭ по математике',
    created_at: '2025-01-15T10:00:00Z',
    student_id: 42,
  },
  {
    id: 2,
    name: 'Максим Иванов',
    status: 'active',
    kind: 'individual',
    description: 'Подготовка к ОГЭ по русскому языку',
    created_at: '2025-01-16T11:30:00Z',
    student_id: 38,
  },
  {
    id: 3,
    name: 'Елизавета Петрова',
    status: 'active',
    kind: 'individual',
    description: 'Изучение английского языка с нуля',
    created_at: '2025-01-17T09:15:00Z',
    student_id: 45,
  },
  {
    id: 4,
    name: 'Дмитрий Кузнецов',
    status: 'active',
    kind: 'individual',
    description: 'Подготовка к ЕГЭ по физике',
    created_at: '2025-01-18T14:20:00Z',
    student_id: 51,
  },
  {
    id: 5,
    name: 'Андрей Соколов',
    status: 'active',
    kind: 'individual',
    description: 'Подготовка к ЕГЭ по химии',
    created_at: '2025-01-19T16:45:00Z',
    student_id: 47,
  },
  {
    id: 6,
    name: 'Кирилл Лебедев',
    status: 'paused',
    kind: 'individual',
    description: 'Подготовка к ЕГЭ по биологии',
    created_at: '2025-01-20T13:00:00Z',
    student_id: 53,
  },
  {
    id: 7,
    name: 'Наталья Орлова',
    status: 'finished',
    kind: 'individual',
    description: 'Подготовка к ЕГЭ по истории',
    created_at: '2025-01-21T15:30:00Z',
    student_id: 49,
  },
  {
    id: 8,
    name: 'English Group',
    status: 'active',
    kind: 'group',
    description: 'Курс по английскому языку для группы',
    created_at: '2025-01-22T12:00:00Z',
  },
  {
    id: 9,
    name: 'Math Group',
    status: 'active',
    kind: 'group',
    description: 'Курс по математике для группы',
    created_at: '2025-01-23T10:30:00Z',
  },
  {
    id: 10,
    name: 'Physics Group',
    status: 'paused',
    kind: 'group',
    description: 'Курс по физике для группы',
    created_at: '2025-01-24T11:45:00Z',
  },
  {
    id: 11,
    name: 'Chemistry Group',
    status: 'active',
    kind: 'group',
    description: 'Курс по химии для группы',
    created_at: '2025-01-25T14:15:00Z',
  },
  {
    id: 12,
    name: 'Biology Group',
    status: 'paused',
    kind: 'group',
    description: 'Курс по биологии для группы',
    created_at: '2025-01-26T16:30:00Z',
  },
  {
    id: 111,
    name: 'Анна Смирнова',
    status: 'active',
    kind: 'individual',
    description: 'Подготовка к ЕГЭ по математике',
    created_at: '2025-01-15T10:00:00Z',
    student_id: 42,
  },
  {
    id: 112,
    name: 'Максим Иванов',
    status: 'active',
    kind: 'individual',
    description: 'Подготовка к ОГЭ по русскому языку',
    created_at: '2025-01-16T11:30:00Z',
    student_id: 38,
  },
  {
    id: 113,
    name: 'Елизавета Петрова',
    status: 'active',
    kind: 'individual',
    description: 'Изучение английского языка с нуля',
    created_at: '2025-01-17T09:15:00Z',
    student_id: 45,
  },
  {
    id: 114,
    name: 'Дмитрий Кузнецов',
    status: 'active',
    kind: 'individual',
    description: 'Подготовка к ЕГЭ по физике',
    created_at: '2025-01-18T14:20:00Z',
    student_id: 51,
  },
  {
    id: 115,
    name: 'Андрей Соколов',
    status: 'active',
    kind: 'individual',
    description: 'Подготовка к ЕГЭ по химии',
    created_at: '2025-01-19T16:45:00Z',
    student_id: 47,
  },
  {
    id: 116,
    name: 'Кирилл Лебедев',
    status: 'paused',
    kind: 'individual',
    description: 'Подготовка к ЕГЭ по биологии',
    created_at: '2025-01-20T13:00:00Z',
    student_id: 53,
  },
  {
    id: 117,
    name: 'Наталья Орлова',
    status: 'finished',
    kind: 'individual',
    description: 'Подготовка к ЕГЭ по истории',
    created_at: '2025-01-21T15:30:00Z',
    student_id: 49,
  },
  {
    id: 118,
    name: 'English Group',
    status: 'active',
    kind: 'group',
    description: 'Курс по английскому языку для группы',
    created_at: '2025-01-22T12:00:00Z',
  },
  {
    id: 119,
    name: 'Math Group',
    status: 'active',
    kind: 'group',
    description: 'Курс по математике для группы',
    created_at: '2025-01-23T10:30:00Z',
  },
  {
    id: 120,
    name: 'Physics Group',
    status: 'paused',
    kind: 'group',
    description: 'Курс по физике для группы',
    created_at: '2025-01-24T11:45:00Z',
  },
  {
    id: 121,
    name: 'Chemistry Group',
    status: 'active',
    kind: 'group',
    description: 'Курс по химии для группы',
    created_at: '2025-01-25T14:15:00Z',
  },
  {
    id: 1112,
    name: 'Biology Group',
    status: 'paused',
    kind: 'group',
    description: 'Курс по биологии для группы',
    created_at: '2025-01-26T16:30:00Z',
  },
];
