//! Entry point of the Sovlium native shell.
//!
//! The actual application bootstrap lives here (rather than in `main.rs`) so
//! that the same code path is reused on iOS and Android, where Tauri loads the
//! crate as a dynamic library and calls `run()` from generated glue code.

mod commands;
mod media;
mod navigation;
mod setup;
mod share_overlay;
mod webview_policy;

/// The `#[cfg_attr]` attribute exposes `run` to the mobile entry points
/// generated by `tauri ios|android init`.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let mut builder = tauri::Builder::default();

    // Cross-platform plugins.
    builder = builder
        .plugin(tauri_plugin_log::Builder::default().build())
        .plugin(tauri_plugin_os::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_deep_link::init())
        .plugin(tauri_plugin_clipboard_manager::init())
        .plugin(tauri_plugin_opener::init())
        // Restrict top-level navigations to *.sovlium.ru (+ local schemes).
        .plugin(navigation::init())
        // Mark WebView as native + disable Yandex Metrika inside the shell.
        .plugin(webview_policy::init());

    // Desktop-only plugins. Keeping these behind `cfg(desktop)` prevents the
    // mobile build from pulling in unsupported native targets.
    #[cfg(desktop)]
    {
        builder = builder
            .plugin(tauri_plugin_updater::Builder::new().build())
            .plugin(tauri_plugin_process::init())
            .plugin(tauri_plugin_single_instance::init(|app, _argv, _cwd| {
                // Single-instance handler: focus the existing window instead of
                // launching a second copy. We use the main window's label as
                // declared in `tauri.conf.json`.
                use tauri::Manager;
                if let Some(window) = app.get_webview_window("main") {
                    let _ = window.set_focus();
                    let _ = window.unminimize();
                }
            }));
    }

    builder
        .setup(setup::setup)
        .invoke_handler(tauri::generate_handler![
            commands::app_info,
            commands::log_message,
            commands::http_probe,
            commands::save_file,
            media::media_permission_status,
            media::media_permission_request,
            share_overlay::share_overlay_show,
            share_overlay::share_overlay_hide,
            share_overlay::share_overlay_focus_main,
            share_overlay::share_overlay_request_stop,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
