export const IPC = {
  appGetInfo: 'sovlium:app:get-info',
  appGetPlatform: 'sovlium:app:get-platform',
  windowMinimize: 'sovlium:window:minimize',
  windowMaximize: 'sovlium:window:maximize',
  windowClose: 'sovlium:window:close',
  windowFocus: 'sovlium:window:focus',
  windowUnminimize: 'sovlium:window:unminimize',
  windowIsMinimized: 'sovlium:window:is-minimized',
  windowSetTitle: 'sovlium:window:set-title',
  conferenceStart: 'sovlium:conference:start',
  conferenceLeave: 'sovlium:conference:leave',
  conferenceSetSlotBounds: 'sovlium:conference:set-slot-bounds',
  conferenceEnterFloating: 'sovlium:conference:enter-floating',
  conferenceExitFloating: 'sovlium:conference:exit-floating',
  conferenceResizeFloating: 'sovlium:conference:resize-floating',
  conferenceGetState: 'sovlium:conference:get-state',
  conferenceEnded: 'sovlium:conference:ended',
  screenShareOpenControls: 'sovlium:share:open-controls',
  screenShareCloseControls: 'sovlium:share:close-controls',
  screenShareFocusMain: 'sovlium:share:focus-main',
  screenShareRequestStop: 'sovlium:share:request-stop',
  screenShareListSources: 'sovlium:share:list-sources',
  screenShareSelectSource: 'sovlium:share:select-source',
  screenShareLayoutAnnotations: 'sovlium:share:layout-annotations',
  screenShareSetAnnotationDrawing: 'sovlium:share:set-annotation-drawing',
  screenShareSetToolbarHeight: 'sovlium:share:set-toolbar-height',
  remoteControlStatus: 'sovlium:remote-control:status',
  remoteControlRequestAccess: 'sovlium:remote-control:request-access',
  remoteControlSetActive: 'sovlium:remote-control:set-active',
  remoteControlInput: 'sovlium:remote-control:input',
  filesSave: 'sovlium:files:save',
  externalOpenUrl: 'sovlium:external:open-url',
  permissionsStatus: 'sovlium:permissions:status',
  permissionsRequest: 'sovlium:permissions:request',
  themeGet: 'sovlium:theme:get',
  themeSet: 'sovlium:theme:set',
  notificationsStatus: 'sovlium:notifications:status',
  notificationsRequest: 'sovlium:notifications:request',
  notificationsShow: 'sovlium:notifications:show',
  clipboardWriteText: 'sovlium:clipboard:write-text',
  clipboardReadText: 'sovlium:clipboard:read-text',
  clipboardWriteHtml: 'sovlium:clipboard:write-html',
  clipboardReadHtml: 'sovlium:clipboard:read-html',
  powerSetDisplaySleepBlocked: 'sovlium:power:set-display-sleep-blocked',
  updaterGetState: 'sovlium:updater:get-state',
  updaterCheck: 'sovlium:updater:check',
  updaterDownload: 'sovlium:updater:download',
  updaterInstall: 'sovlium:updater:install',
  updaterOpenRelease: 'sovlium:updater:open-release',
} as const;

export type IpcChannel = (typeof IPC)[keyof typeof IPC];

export const EVENTS = {
  conferenceState: 'sovlium:event:conference-state',
  windowFocus: 'sovlium:event:window-focus',
  deepLink: 'sovlium:event:deep-link',
  shareOverlayStop: 'share-overlay-stop',
  shareAnnotation: 'share-annotate-stroke',
  callPipRestored: 'call-pip-restored',
  notificationClick: 'sovlium:event:notification-click',
  updaterState: 'sovlium:event:updater-state',
} as const;

export type EventChannel = (typeof EVENTS)[keyof typeof EVENTS];
