/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './pages/__root'
import { Route as appLayoutRouteImport } from './pages/(app)/_layout'
import { Route as authSignupIndexRouteImport } from './pages/(auth)/signup/index'
import { Route as authSigninIndexRouteImport } from './pages/(auth)/signin/index'
import { Route as authResetPasswordIndexRouteImport } from './pages/(auth)/reset-password/index'
import { Route as appLayoutIndexRouteImport } from './pages/(app)/_layout/index'
import { Route as DeploymentsDeploymentIdEnableRouteImport } from './pages/deployments/$deploymentId.enable'
import { Route as authResetPasswordResetTokenRouteImport } from './pages/(auth)/reset-password/$resetToken'
import { Route as appWelcomeLayoutRouteImport } from './pages/(app)/welcome/_layout'
import { Route as appInviteInviteIdRouteImport } from './pages/(app)/invite/$inviteId'
import { Route as appWelcomeUserIndexRouteImport } from './pages/(app)/welcome/user/index'
import { Route as appWelcomeSocialsIndexRouteImport } from './pages/(app)/welcome/socials/index'
import { Route as appWelcomeRoleIndexRouteImport } from './pages/(app)/welcome/role/index'
import { Route as appLayoutPaymentsIndexRouteImport } from './pages/(app)/_layout/payments/index'
import { Route as appLayoutMaterialsIndexRouteImport } from './pages/(app)/_layout/materials/index'
import { Route as appLayoutClassroomsIndexRouteImport } from './pages/(app)/_layout/classrooms/index'
import { Route as appLayoutCallIndexRouteImport } from './pages/(app)/_layout/call/index'
import { Route as appLayoutCalendarIndexRouteImport } from './pages/(app)/_layout/calendar/index'
import { Route as appLayoutEditorEditorIdRouteImport } from './pages/(app)/_layout/note/$noteId'
import { Route as appLayoutClassroomsClassroomIdRouteImport } from './pages/(app)/_layout/classrooms/$classroomId'
import { Route as appLayoutCallCallIdRouteImport } from './pages/(app)/_layout/call/$callId'
import { Route as appLayoutBoardBoardIdRouteImport } from './pages/(app)/_layout/board/$boardId'

const appWelcomeRouteImport = createFileRoute('/(app)/welcome')()

const appWelcomeRoute = appWelcomeRouteImport.update({
  id: '/(app)/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRoute = appLayoutRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupIndexRoute = authSignupIndexRouteImport.update({
  id: '/(auth)/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninIndexRoute = authSigninIndexRouteImport.update({
  id: '/(auth)/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordIndexRoute = authResetPasswordIndexRouteImport.update({
  id: '/(auth)/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutIndexRoute = appLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLayoutRoute,
} as any)
const DeploymentsDeploymentIdEnableRoute =
  DeploymentsDeploymentIdEnableRouteImport.update({
    id: '/deployments/$deploymentId/enable',
    path: '/deployments/$deploymentId/enable',
    getParentRoute: () => rootRouteImport,
  } as any)
const authResetPasswordResetTokenRoute =
  authResetPasswordResetTokenRouteImport.update({
    id: '/(auth)/reset-password/$resetToken',
    path: '/reset-password/$resetToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const appWelcomeLayoutRoute = appWelcomeLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => appWelcomeRoute,
} as any)
const appInviteInviteIdRoute = appInviteInviteIdRouteImport.update({
  id: '/(app)/invite/$inviteId',
  path: '/invite/$inviteId',
  getParentRoute: () => rootRouteImport,
} as any)
const appWelcomeUserIndexRoute = appWelcomeUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => appWelcomeRoute,
} as any)
const appWelcomeSocialsIndexRoute = appWelcomeSocialsIndexRouteImport.update({
  id: '/socials/',
  path: '/socials/',
  getParentRoute: () => appWelcomeRoute,
} as any)
const appWelcomeRoleIndexRoute = appWelcomeRoleIndexRouteImport.update({
  id: '/role/',
  path: '/role/',
  getParentRoute: () => appWelcomeRoute,
} as any)
const appLayoutPaymentsIndexRoute = appLayoutPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutMaterialsIndexRoute = appLayoutMaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutClassroomsIndexRoute =
  appLayoutClassroomsIndexRouteImport.update({
    id: '/classrooms/',
    path: '/classrooms/',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutCallIndexRoute = appLayoutCallIndexRouteImport.update({
  id: '/call/',
  path: '/call/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutCalendarIndexRoute = appLayoutCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutEditorEditorIdRoute = appLayoutEditorEditorIdRouteImport.update({
  id: '/note/$noteId',
  path: '/note/$noteId',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutClassroomsClassroomIdRoute =
  appLayoutClassroomsClassroomIdRouteImport.update({
    id: '/classrooms/$classroomId',
    path: '/classrooms/$classroomId',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutCallCallIdRoute = appLayoutCallCallIdRouteImport.update({
  id: '/call/$callId',
  path: '/call/$callId',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutBoardBoardIdRoute = appLayoutBoardBoardIdRouteImport.update({
  id: '/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => appLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/invite/$inviteId': typeof appInviteInviteIdRoute
  '/welcome': typeof appWelcomeLayoutRoute
  '/reset-password/$resetToken': typeof authResetPasswordResetTokenRoute
  '/deployments/$deploymentId/enable': typeof DeploymentsDeploymentIdEnableRoute
  '/': typeof appLayoutIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/signin': typeof authSigninIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/board/$boardId': typeof appLayoutBoardBoardIdRoute
  '/call/$callId': typeof appLayoutCallCallIdRoute
  '/classrooms/$classroomId': typeof appLayoutClassroomsClassroomIdRoute
  '/note/$editorId': typeof appLayoutEditorEditorIdRoute
  '/calendar': typeof appLayoutCalendarIndexRoute
  '/call': typeof appLayoutCallIndexRoute
  '/classrooms': typeof appLayoutClassroomsIndexRoute
  '/materials': typeof appLayoutMaterialsIndexRoute
  '/payments': typeof appLayoutPaymentsIndexRoute
  '/welcome/role': typeof appWelcomeRoleIndexRoute
  '/welcome/socials': typeof appWelcomeSocialsIndexRoute
  '/welcome/user': typeof appWelcomeUserIndexRoute
}
export interface FileRoutesByTo {
  '/invite/$inviteId': typeof appInviteInviteIdRoute
  '/welcome': typeof appWelcomeLayoutRoute
  '/reset-password/$resetToken': typeof authResetPasswordResetTokenRoute
  '/deployments/$deploymentId/enable': typeof DeploymentsDeploymentIdEnableRoute
  '/': typeof appLayoutIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/signin': typeof authSigninIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/board/$boardId': typeof appLayoutBoardBoardIdRoute
  '/call/$callId': typeof appLayoutCallCallIdRoute
  '/classrooms/$classroomId': typeof appLayoutClassroomsClassroomIdRoute
  '/note/$editorId': typeof appLayoutEditorEditorIdRoute
  '/calendar': typeof appLayoutCalendarIndexRoute
  '/call': typeof appLayoutCallIndexRoute
  '/classrooms': typeof appLayoutClassroomsIndexRoute
  '/materials': typeof appLayoutMaterialsIndexRoute
  '/payments': typeof appLayoutPaymentsIndexRoute
  '/welcome/role': typeof appWelcomeRoleIndexRoute
  '/welcome/socials': typeof appWelcomeSocialsIndexRoute
  '/welcome/user': typeof appWelcomeUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_layout': typeof appLayoutRouteWithChildren
  '/(app)/invite/$inviteId': typeof appInviteInviteIdRoute
  '/(app)/welcome': typeof appWelcomeRouteWithChildren
  '/(app)/welcome/_layout': typeof appWelcomeLayoutRoute
  '/(auth)/reset-password/$resetToken': typeof authResetPasswordResetTokenRoute
  '/deployments/$deploymentId/enable': typeof DeploymentsDeploymentIdEnableRoute
  '/(app)/_layout/': typeof appLayoutIndexRoute
  '/(auth)/reset-password/': typeof authResetPasswordIndexRoute
  '/(auth)/signin/': typeof authSigninIndexRoute
  '/(auth)/signup/': typeof authSignupIndexRoute
  '/(app)/_layout/board/$boardId': typeof appLayoutBoardBoardIdRoute
  '/(app)/_layout/call/$callId': typeof appLayoutCallCallIdRoute
  '/(app)/_layout/classrooms/$classroomId': typeof appLayoutClassroomsClassroomIdRoute
  '/(app)/_layout/note/$noteId': typeof appLayoutEditorEditorIdRoute
  '/(app)/_layout/calendar/': typeof appLayoutCalendarIndexRoute
  '/(app)/_layout/call/': typeof appLayoutCallIndexRoute
  '/(app)/_layout/classrooms/': typeof appLayoutClassroomsIndexRoute
  '/(app)/_layout/materials/': typeof appLayoutMaterialsIndexRoute
  '/(app)/_layout/payments/': typeof appLayoutPaymentsIndexRoute
  '/(app)/welcome/role/': typeof appWelcomeRoleIndexRoute
  '/(app)/welcome/socials/': typeof appWelcomeSocialsIndexRoute
  '/(app)/welcome/user/': typeof appWelcomeUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/invite/$inviteId'
    | '/welcome'
    | '/reset-password/$resetToken'
    | '/deployments/$deploymentId/enable'
    | '/'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/board/$boardId'
    | '/call/$callId'
    | '/classrooms/$classroomId'
    | '/note/$noteId'
    | '/calendar'
    | '/call'
    | '/classrooms'
    | '/materials'
    | '/payments'
    | '/welcome/role'
    | '/welcome/socials'
    | '/welcome/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/invite/$inviteId'
    | '/welcome'
    | '/reset-password/$resetToken'
    | '/deployments/$deploymentId/enable'
    | '/'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/board/$boardId'
    | '/call/$callId'
    | '/classrooms/$classroomId'
    | '/note/$noteId'
    | '/calendar'
    | '/call'
    | '/classrooms'
    | '/materials'
    | '/payments'
    | '/welcome/role'
    | '/welcome/socials'
    | '/welcome/user'
  id:
    | '__root__'
    | '/(app)/_layout'
    | '/(app)/invite/$inviteId'
    | '/(app)/welcome'
    | '/(app)/welcome/_layout'
    | '/(auth)/reset-password/$resetToken'
    | '/deployments/$deploymentId/enable'
    | '/(app)/_layout/'
    | '/(auth)/reset-password/'
    | '/(auth)/signin/'
    | '/(auth)/signup/'
    | '/(app)/_layout/board/$boardId'
    | '/(app)/_layout/call/$callId'
    | '/(app)/_layout/classrooms/$classroomId'
    | '/(app)/_layout/note/$noteId'
    | '/(app)/_layout/calendar/'
    | '/(app)/_layout/call/'
    | '/(app)/_layout/classrooms/'
    | '/(app)/_layout/materials/'
    | '/(app)/_layout/payments/'
    | '/(app)/welcome/role/'
    | '/(app)/welcome/socials/'
    | '/(app)/welcome/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appLayoutRoute: typeof appLayoutRouteWithChildren
  appInviteInviteIdRoute: typeof appInviteInviteIdRoute
  appWelcomeRoute: typeof appWelcomeRouteWithChildren
  authResetPasswordResetTokenRoute: typeof authResetPasswordResetTokenRoute
  DeploymentsDeploymentIdEnableRoute: typeof DeploymentsDeploymentIdEnableRoute
  authResetPasswordIndexRoute: typeof authResetPasswordIndexRoute
  authSigninIndexRoute: typeof authSigninIndexRoute
  authSignupIndexRoute: typeof authSignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/welcome': {
      id: '/(app)/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof appWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup/': {
      id: '/(auth)/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin/': {
      id: '/(auth)/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password/': {
      id: '/(auth)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/': {
      id: '/(app)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appLayoutIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/deployments/$deploymentId/enable': {
      id: '/deployments/$deploymentId/enable'
      path: '/deployments/$deploymentId/enable'
      fullPath: '/deployments/$deploymentId/enable'
      preLoaderRoute: typeof DeploymentsDeploymentIdEnableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password/$resetToken': {
      id: '/(auth)/reset-password/$resetToken'
      path: '/reset-password/$resetToken'
      fullPath: '/reset-password/$resetToken'
      preLoaderRoute: typeof authResetPasswordResetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/welcome/_layout': {
      id: '/(app)/welcome/_layout'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof appWelcomeLayoutRouteImport
      parentRoute: typeof appWelcomeRoute
    }
    '/(app)/invite/$inviteId': {
      id: '/(app)/invite/$inviteId'
      path: '/invite/$inviteId'
      fullPath: '/invite/$inviteId'
      preLoaderRoute: typeof appInviteInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/welcome/user/': {
      id: '/(app)/welcome/user/'
      path: '/user'
      fullPath: '/welcome/user'
      preLoaderRoute: typeof appWelcomeUserIndexRouteImport
      parentRoute: typeof appWelcomeRoute
    }
    '/(app)/welcome/socials/': {
      id: '/(app)/welcome/socials/'
      path: '/socials'
      fullPath: '/welcome/socials'
      preLoaderRoute: typeof appWelcomeSocialsIndexRouteImport
      parentRoute: typeof appWelcomeRoute
    }
    '/(app)/welcome/role/': {
      id: '/(app)/welcome/role/'
      path: '/role'
      fullPath: '/welcome/role'
      preLoaderRoute: typeof appWelcomeRoleIndexRouteImport
      parentRoute: typeof appWelcomeRoute
    }
    '/(app)/_layout/payments/': {
      id: '/(app)/_layout/payments/'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof appLayoutPaymentsIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/materials/': {
      id: '/(app)/_layout/materials/'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof appLayoutMaterialsIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/classrooms/': {
      id: '/(app)/_layout/classrooms/'
      path: '/classrooms'
      fullPath: '/classrooms'
      preLoaderRoute: typeof appLayoutClassroomsIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/call/': {
      id: '/(app)/_layout/call/'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof appLayoutCallIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/calendar/': {
      id: '/(app)/_layout/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof appLayoutCalendarIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/note/$editorId': {
      id: '/(app)/_layout/note/$editorId'
      path: '/note/$editorId'
      fullPath: '/note/$editorId'
      preLoaderRoute: typeof appLayoutEditorEditorIdRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/classrooms/$classroomId': {
      id: '/(app)/_layout/classrooms/$classroomId'
      path: '/classrooms/$classroomId'
      fullPath: '/classrooms/$classroomId'
      preLoaderRoute: typeof appLayoutClassroomsClassroomIdRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/call/$callId': {
      id: '/(app)/_layout/call/$callId'
      path: '/call/$callId'
      fullPath: '/call/$callId'
      preLoaderRoute: typeof appLayoutCallCallIdRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/board/$boardId': {
      id: '/(app)/_layout/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof appLayoutBoardBoardIdRouteImport
      parentRoute: typeof appLayoutRoute
    }
  }
}

interface appLayoutRouteChildren {
  appLayoutIndexRoute: typeof appLayoutIndexRoute
  appLayoutBoardBoardIdRoute: typeof appLayoutBoardBoardIdRoute
  appLayoutCallCallIdRoute: typeof appLayoutCallCallIdRoute
  appLayoutClassroomsClassroomIdRoute: typeof appLayoutClassroomsClassroomIdRoute
  appLayoutEditorEditorIdRoute: typeof appLayoutEditorEditorIdRoute
  appLayoutCalendarIndexRoute: typeof appLayoutCalendarIndexRoute
  appLayoutCallIndexRoute: typeof appLayoutCallIndexRoute
  appLayoutClassroomsIndexRoute: typeof appLayoutClassroomsIndexRoute
  appLayoutMaterialsIndexRoute: typeof appLayoutMaterialsIndexRoute
  appLayoutPaymentsIndexRoute: typeof appLayoutPaymentsIndexRoute
}

const appLayoutRouteChildren: appLayoutRouteChildren = {
  appLayoutIndexRoute: appLayoutIndexRoute,
  appLayoutBoardBoardIdRoute: appLayoutBoardBoardIdRoute,
  appLayoutCallCallIdRoute: appLayoutCallCallIdRoute,
  appLayoutClassroomsClassroomIdRoute: appLayoutClassroomsClassroomIdRoute,
  appLayoutEditorEditorIdRoute: appLayoutEditorEditorIdRoute,
  appLayoutCalendarIndexRoute: appLayoutCalendarIndexRoute,
  appLayoutCallIndexRoute: appLayoutCallIndexRoute,
  appLayoutClassroomsIndexRoute: appLayoutClassroomsIndexRoute,
  appLayoutMaterialsIndexRoute: appLayoutMaterialsIndexRoute,
  appLayoutPaymentsIndexRoute: appLayoutPaymentsIndexRoute,
}

const appLayoutRouteWithChildren = appLayoutRoute._addFileChildren(
  appLayoutRouteChildren,
)

interface appWelcomeRouteChildren {
  appWelcomeLayoutRoute: typeof appWelcomeLayoutRoute
  appWelcomeRoleIndexRoute: typeof appWelcomeRoleIndexRoute
  appWelcomeSocialsIndexRoute: typeof appWelcomeSocialsIndexRoute
  appWelcomeUserIndexRoute: typeof appWelcomeUserIndexRoute
}

const appWelcomeRouteChildren: appWelcomeRouteChildren = {
  appWelcomeLayoutRoute: appWelcomeLayoutRoute,
  appWelcomeRoleIndexRoute: appWelcomeRoleIndexRoute,
  appWelcomeSocialsIndexRoute: appWelcomeSocialsIndexRoute,
  appWelcomeUserIndexRoute: appWelcomeUserIndexRoute,
}

const appWelcomeRouteWithChildren = appWelcomeRoute._addFileChildren(
  appWelcomeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appLayoutRoute: appLayoutRouteWithChildren,
  appInviteInviteIdRoute: appInviteInviteIdRoute,
  appWelcomeRoute: appWelcomeRouteWithChildren,
  authResetPasswordResetTokenRoute: authResetPasswordResetTokenRoute,
  DeploymentsDeploymentIdEnableRoute: DeploymentsDeploymentIdEnableRoute,
  authResetPasswordIndexRoute: authResetPasswordIndexRoute,
  authSigninIndexRoute: authSigninIndexRoute,
  authSignupIndexRoute: authSignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
