/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as commonLayoutRouteImport } from './pages/(common)/_layout'
import { Route as appLayoutRouteImport } from './pages/(app)/_layout'
import { Route as authSignupIndexRouteImport } from './pages/(auth)/signup/index'
import { Route as authSigninIndexRouteImport } from './pages/(auth)/signin/index'
import { Route as authResetPasswordIndexRouteImport } from './pages/(auth)/reset-password/index'
import { Route as appLayoutIndexRouteImport } from './pages/(app)/_layout/index'
import { Route as DeploymentsDeploymentIdEnableRouteImport } from './pages/deployments/$deploymentId.enable'
import { Route as authResetPasswordResetTokenRouteImport } from './pages/(auth)/reset-password/$resetToken'
import { Route as commonWelcomeUserIndexRouteImport } from './pages/(common)/welcome/user/index'
import { Route as commonWelcomeSocialsIndexRouteImport } from './pages/(common)/welcome/socials/index'
import { Route as commonWelcomeRoleIndexRouteImport } from './pages/(common)/welcome/role/index'
import { Route as appLayoutPaymentsIndexRouteImport } from './pages/(app)/_layout/payments/index'
import { Route as appLayoutMaterialsIndexRouteImport } from './pages/(app)/_layout/materials/index'
import { Route as appLayoutClassroomsIndexRouteImport } from './pages/(app)/_layout/classrooms/index'
import { Route as appLayoutCallIndexRouteImport } from './pages/(app)/_layout/call/index'
import { Route as appLayoutCalendarIndexRouteImport } from './pages/(app)/_layout/calendar/index'
import { Route as commonWelcomeEmailEmailIdRouteImport } from './pages/(common)/welcome/email/$emailId'
import { Route as commonLayoutInviteInviteIdRouteImport } from './pages/(common)/_layout/invite/$inviteId'
import { Route as commonLayoutConfirmEmailEmailIdRouteImport } from './pages/(common)/_layout/confirm-email/$emailId'
import { Route as appLayoutCallCallIdRouteImport } from './pages/(app)/_layout/call/$callId'
import { Route as appLayoutBoardBoardIdRouteImport } from './pages/(app)/_layout/board/$boardId'
import { Route as appLayoutClassroomsClassroomIdIndexRouteImport } from './pages/(app)/_layout/classrooms/$classroomId/index'
import { Route as appLayoutMaterialsMaterialIdNoteIndexRouteImport } from './pages/(app)/_layout/materials/$materialId/note/index'
import { Route as appLayoutMaterialsMaterialIdBoardIndexRouteImport } from './pages/(app)/_layout/materials/$materialId/board/index'
import { Route as appLayoutClassroomsClassroomIdNotesNoteIdRouteImport } from './pages/(app)/_layout/classrooms/$classroomId/notes/$noteId'
import { Route as appLayoutClassroomsClassroomIdBoardsBoardIdRouteImport } from './pages/(app)/_layout/classrooms/$classroomId/boards/$boardId'

const commonLayoutRoute = commonLayoutRouteImport.update({
  id: '/(common)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutRoute = appLayoutRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupIndexRoute = authSignupIndexRouteImport.update({
  id: '/(auth)/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSigninIndexRoute = authSigninIndexRouteImport.update({
  id: '/(auth)/signin/',
  path: '/signin/',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordIndexRoute = authResetPasswordIndexRouteImport.update({
  id: '/(auth)/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutIndexRoute = appLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLayoutRoute,
} as any)
const DeploymentsDeploymentIdEnableRoute =
  DeploymentsDeploymentIdEnableRouteImport.update({
    id: '/deployments/$deploymentId/enable',
    path: '/deployments/$deploymentId/enable',
    getParentRoute: () => rootRouteImport,
  } as any)
const authResetPasswordResetTokenRoute =
  authResetPasswordResetTokenRouteImport.update({
    id: '/(auth)/reset-password/$resetToken',
    path: '/reset-password/$resetToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const commonWelcomeUserIndexRoute = commonWelcomeUserIndexRouteImport.update({
  id: '/(common)/welcome/user/',
  path: '/welcome/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const commonWelcomeSocialsIndexRoute =
  commonWelcomeSocialsIndexRouteImport.update({
    id: '/(common)/welcome/socials/',
    path: '/welcome/socials/',
    getParentRoute: () => rootRouteImport,
  } as any)
const commonWelcomeRoleIndexRoute = commonWelcomeRoleIndexRouteImport.update({
  id: '/(common)/welcome/role/',
  path: '/welcome/role/',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutPaymentsIndexRoute = appLayoutPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutMaterialsIndexRoute = appLayoutMaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutClassroomsIndexRoute =
  appLayoutClassroomsIndexRouteImport.update({
    id: '/classrooms/',
    path: '/classrooms/',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutCallIndexRoute = appLayoutCallIndexRouteImport.update({
  id: '/call/',
  path: '/call/',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutCalendarIndexRoute = appLayoutCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => appLayoutRoute,
} as any)
const commonWelcomeEmailEmailIdRoute =
  commonWelcomeEmailEmailIdRouteImport.update({
    id: '/(common)/welcome/email/$emailId',
    path: '/welcome/email/$emailId',
    getParentRoute: () => rootRouteImport,
  } as any)
const commonLayoutInviteInviteIdRoute =
  commonLayoutInviteInviteIdRouteImport.update({
    id: '/invite/$inviteId',
    path: '/invite/$inviteId',
    getParentRoute: () => commonLayoutRoute,
  } as any)
const commonLayoutConfirmEmailEmailIdRoute =
  commonLayoutConfirmEmailEmailIdRouteImport.update({
    id: '/confirm-email/$emailId',
    path: '/confirm-email/$emailId',
    getParentRoute: () => commonLayoutRoute,
  } as any)
const appLayoutCallCallIdRoute = appLayoutCallCallIdRouteImport.update({
  id: '/call/$callId',
  path: '/call/$callId',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutBoardBoardIdRoute = appLayoutBoardBoardIdRouteImport.update({
  id: '/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => appLayoutRoute,
} as any)
const appLayoutClassroomsClassroomIdIndexRoute =
  appLayoutClassroomsClassroomIdIndexRouteImport.update({
    id: '/classrooms/$classroomId/',
    path: '/classrooms/$classroomId/',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutMaterialsMaterialIdNoteIndexRoute =
  appLayoutMaterialsMaterialIdNoteIndexRouteImport.update({
    id: '/materials/$materialId/note/',
    path: '/materials/$materialId/note/',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutMaterialsMaterialIdBoardIndexRoute =
  appLayoutMaterialsMaterialIdBoardIndexRouteImport.update({
    id: '/materials/$materialId/board/',
    path: '/materials/$materialId/board/',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutClassroomsClassroomIdNotesNoteIdRoute =
  appLayoutClassroomsClassroomIdNotesNoteIdRouteImport.update({
    id: '/classrooms/$classroomId/notes/$noteId',
    path: '/classrooms/$classroomId/notes/$noteId',
    getParentRoute: () => appLayoutRoute,
  } as any)
const appLayoutClassroomsClassroomIdBoardsBoardIdRoute =
  appLayoutClassroomsClassroomIdBoardsBoardIdRouteImport.update({
    id: '/classrooms/$classroomId/boards/$boardId',
    path: '/classrooms/$classroomId/boards/$boardId',
    getParentRoute: () => appLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/reset-password/$resetToken': typeof authResetPasswordResetTokenRoute
  '/deployments/$deploymentId/enable': typeof DeploymentsDeploymentIdEnableRoute
  '/': typeof appLayoutIndexRoute
  '/reset-password/': typeof authResetPasswordIndexRoute
  '/signin/': typeof authSigninIndexRoute
  '/signup/': typeof authSignupIndexRoute
  '/board/$boardId': typeof appLayoutBoardBoardIdRoute
  '/call/$callId': typeof appLayoutCallCallIdRoute
  '/confirm-email/$emailId': typeof commonLayoutConfirmEmailEmailIdRoute
  '/invite/$inviteId': typeof commonLayoutInviteInviteIdRoute
  '/welcome/email/$emailId': typeof commonWelcomeEmailEmailIdRoute
  '/calendar/': typeof appLayoutCalendarIndexRoute
  '/call/': typeof appLayoutCallIndexRoute
  '/classrooms/': typeof appLayoutClassroomsIndexRoute
  '/materials/': typeof appLayoutMaterialsIndexRoute
  '/payments/': typeof appLayoutPaymentsIndexRoute
  '/welcome/role/': typeof commonWelcomeRoleIndexRoute
  '/welcome/socials/': typeof commonWelcomeSocialsIndexRoute
  '/welcome/user/': typeof commonWelcomeUserIndexRoute
  '/classrooms/$classroomId/': typeof appLayoutClassroomsClassroomIdIndexRoute
  '/classrooms/$classroomId/boards/$boardId': typeof appLayoutClassroomsClassroomIdBoardsBoardIdRoute
  '/classrooms/$classroomId/notes/$noteId': typeof appLayoutClassroomsClassroomIdNotesNoteIdRoute
  '/materials/$materialId/board/': typeof appLayoutMaterialsMaterialIdBoardIndexRoute
  '/materials/$materialId/note/': typeof appLayoutMaterialsMaterialIdNoteIndexRoute
}
export interface FileRoutesByTo {
  '/reset-password/$resetToken': typeof authResetPasswordResetTokenRoute
  '/deployments/$deploymentId/enable': typeof DeploymentsDeploymentIdEnableRoute
  '/': typeof appLayoutIndexRoute
  '/reset-password': typeof authResetPasswordIndexRoute
  '/signin': typeof authSigninIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/board/$boardId': typeof appLayoutBoardBoardIdRoute
  '/call/$callId': typeof appLayoutCallCallIdRoute
  '/confirm-email/$emailId': typeof commonLayoutConfirmEmailEmailIdRoute
  '/invite/$inviteId': typeof commonLayoutInviteInviteIdRoute
  '/welcome/email/$emailId': typeof commonWelcomeEmailEmailIdRoute
  '/calendar': typeof appLayoutCalendarIndexRoute
  '/call': typeof appLayoutCallIndexRoute
  '/classrooms': typeof appLayoutClassroomsIndexRoute
  '/materials': typeof appLayoutMaterialsIndexRoute
  '/payments': typeof appLayoutPaymentsIndexRoute
  '/welcome/role': typeof commonWelcomeRoleIndexRoute
  '/welcome/socials': typeof commonWelcomeSocialsIndexRoute
  '/welcome/user': typeof commonWelcomeUserIndexRoute
  '/classrooms/$classroomId': typeof appLayoutClassroomsClassroomIdIndexRoute
  '/classrooms/$classroomId/boards/$boardId': typeof appLayoutClassroomsClassroomIdBoardsBoardIdRoute
  '/classrooms/$classroomId/notes/$noteId': typeof appLayoutClassroomsClassroomIdNotesNoteIdRoute
  '/materials/$materialId/board': typeof appLayoutMaterialsMaterialIdBoardIndexRoute
  '/materials/$materialId/note': typeof appLayoutMaterialsMaterialIdNoteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_layout': typeof appLayoutRouteWithChildren
  '/(common)/_layout': typeof commonLayoutRouteWithChildren
  '/(auth)/reset-password/$resetToken': typeof authResetPasswordResetTokenRoute
  '/deployments/$deploymentId/enable': typeof DeploymentsDeploymentIdEnableRoute
  '/(app)/_layout/': typeof appLayoutIndexRoute
  '/(auth)/reset-password/': typeof authResetPasswordIndexRoute
  '/(auth)/signin/': typeof authSigninIndexRoute
  '/(auth)/signup/': typeof authSignupIndexRoute
  '/(app)/_layout/board/$boardId': typeof appLayoutBoardBoardIdRoute
  '/(app)/_layout/call/$callId': typeof appLayoutCallCallIdRoute
  '/(common)/_layout/confirm-email/$emailId': typeof commonLayoutConfirmEmailEmailIdRoute
  '/(common)/_layout/invite/$inviteId': typeof commonLayoutInviteInviteIdRoute
  '/(common)/welcome/email/$emailId': typeof commonWelcomeEmailEmailIdRoute
  '/(app)/_layout/calendar/': typeof appLayoutCalendarIndexRoute
  '/(app)/_layout/call/': typeof appLayoutCallIndexRoute
  '/(app)/_layout/classrooms/': typeof appLayoutClassroomsIndexRoute
  '/(app)/_layout/materials/': typeof appLayoutMaterialsIndexRoute
  '/(app)/_layout/payments/': typeof appLayoutPaymentsIndexRoute
  '/(common)/welcome/role/': typeof commonWelcomeRoleIndexRoute
  '/(common)/welcome/socials/': typeof commonWelcomeSocialsIndexRoute
  '/(common)/welcome/user/': typeof commonWelcomeUserIndexRoute
  '/(app)/_layout/classrooms/$classroomId/': typeof appLayoutClassroomsClassroomIdIndexRoute
  '/(app)/_layout/classrooms/$classroomId/boards/$boardId': typeof appLayoutClassroomsClassroomIdBoardsBoardIdRoute
  '/(app)/_layout/classrooms/$classroomId/notes/$noteId': typeof appLayoutClassroomsClassroomIdNotesNoteIdRoute
  '/(app)/_layout/materials/$materialId/board/': typeof appLayoutMaterialsMaterialIdBoardIndexRoute
  '/(app)/_layout/materials/$materialId/note/': typeof appLayoutMaterialsMaterialIdNoteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/reset-password/$resetToken'
    | '/deployments/$deploymentId/enable'
    | '/'
    | '/reset-password/'
    | '/signin/'
    | '/signup/'
    | '/board/$boardId'
    | '/call/$callId'
    | '/confirm-email/$emailId'
    | '/invite/$inviteId'
    | '/welcome/email/$emailId'
    | '/calendar/'
    | '/call/'
    | '/classrooms/'
    | '/materials/'
    | '/payments/'
    | '/welcome/role/'
    | '/welcome/socials/'
    | '/welcome/user/'
    | '/classrooms/$classroomId/'
    | '/classrooms/$classroomId/boards/$boardId'
    | '/classrooms/$classroomId/notes/$noteId'
    | '/materials/$materialId/board/'
    | '/materials/$materialId/note/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/reset-password/$resetToken'
    | '/deployments/$deploymentId/enable'
    | '/'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/board/$boardId'
    | '/call/$callId'
    | '/confirm-email/$emailId'
    | '/invite/$inviteId'
    | '/welcome/email/$emailId'
    | '/calendar'
    | '/call'
    | '/classrooms'
    | '/materials'
    | '/payments'
    | '/welcome/role'
    | '/welcome/socials'
    | '/welcome/user'
    | '/classrooms/$classroomId'
    | '/classrooms/$classroomId/boards/$boardId'
    | '/classrooms/$classroomId/notes/$noteId'
    | '/materials/$materialId/board'
    | '/materials/$materialId/note'
  id:
    | '__root__'
    | '/(app)/_layout'
    | '/(common)/_layout'
    | '/(auth)/reset-password/$resetToken'
    | '/deployments/$deploymentId/enable'
    | '/(app)/_layout/'
    | '/(auth)/reset-password/'
    | '/(auth)/signin/'
    | '/(auth)/signup/'
    | '/(app)/_layout/board/$boardId'
    | '/(app)/_layout/call/$callId'
    | '/(common)/_layout/confirm-email/$emailId'
    | '/(common)/_layout/invite/$inviteId'
    | '/(common)/welcome/email/$emailId'
    | '/(app)/_layout/calendar/'
    | '/(app)/_layout/call/'
    | '/(app)/_layout/classrooms/'
    | '/(app)/_layout/materials/'
    | '/(app)/_layout/payments/'
    | '/(common)/welcome/role/'
    | '/(common)/welcome/socials/'
    | '/(common)/welcome/user/'
    | '/(app)/_layout/classrooms/$classroomId/'
    | '/(app)/_layout/classrooms/$classroomId/boards/$boardId'
    | '/(app)/_layout/classrooms/$classroomId/notes/$noteId'
    | '/(app)/_layout/materials/$materialId/board/'
    | '/(app)/_layout/materials/$materialId/note/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appLayoutRoute: typeof appLayoutRouteWithChildren
  commonLayoutRoute: typeof commonLayoutRouteWithChildren
  authResetPasswordResetTokenRoute: typeof authResetPasswordResetTokenRoute
  DeploymentsDeploymentIdEnableRoute: typeof DeploymentsDeploymentIdEnableRoute
  authResetPasswordIndexRoute: typeof authResetPasswordIndexRoute
  authSigninIndexRoute: typeof authSigninIndexRoute
  authSignupIndexRoute: typeof authSignupIndexRoute
  commonWelcomeEmailEmailIdRoute: typeof commonWelcomeEmailEmailIdRoute
  commonWelcomeRoleIndexRoute: typeof commonWelcomeRoleIndexRoute
  commonWelcomeSocialsIndexRoute: typeof commonWelcomeSocialsIndexRoute
  commonWelcomeUserIndexRoute: typeof commonWelcomeUserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(common)/_layout': {
      id: '/(common)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof commonLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup/': {
      id: '/(auth)/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof authSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin/': {
      id: '/(auth)/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof authSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password/': {
      id: '/(auth)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof authResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/': {
      id: '/(app)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appLayoutIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/deployments/$deploymentId/enable': {
      id: '/deployments/$deploymentId/enable'
      path: '/deployments/$deploymentId/enable'
      fullPath: '/deployments/$deploymentId/enable'
      preLoaderRoute: typeof DeploymentsDeploymentIdEnableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password/$resetToken': {
      id: '/(auth)/reset-password/$resetToken'
      path: '/reset-password/$resetToken'
      fullPath: '/reset-password/$resetToken'
      preLoaderRoute: typeof authResetPasswordResetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(common)/welcome/user/': {
      id: '/(common)/welcome/user/'
      path: '/welcome/user'
      fullPath: '/welcome/user/'
      preLoaderRoute: typeof commonWelcomeUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(common)/welcome/socials/': {
      id: '/(common)/welcome/socials/'
      path: '/welcome/socials'
      fullPath: '/welcome/socials/'
      preLoaderRoute: typeof commonWelcomeSocialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(common)/welcome/role/': {
      id: '/(common)/welcome/role/'
      path: '/welcome/role'
      fullPath: '/welcome/role/'
      preLoaderRoute: typeof commonWelcomeRoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/payments/': {
      id: '/(app)/_layout/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof appLayoutPaymentsIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/materials/': {
      id: '/(app)/_layout/materials/'
      path: '/materials'
      fullPath: '/materials/'
      preLoaderRoute: typeof appLayoutMaterialsIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/classrooms/': {
      id: '/(app)/_layout/classrooms/'
      path: '/classrooms'
      fullPath: '/classrooms/'
      preLoaderRoute: typeof appLayoutClassroomsIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/call/': {
      id: '/(app)/_layout/call/'
      path: '/call'
      fullPath: '/call/'
      preLoaderRoute: typeof appLayoutCallIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/calendar/': {
      id: '/(app)/_layout/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof appLayoutCalendarIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(common)/welcome/email/$emailId': {
      id: '/(common)/welcome/email/$emailId'
      path: '/welcome/email/$emailId'
      fullPath: '/welcome/email/$emailId'
      preLoaderRoute: typeof commonWelcomeEmailEmailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(common)/_layout/invite/$inviteId': {
      id: '/(common)/_layout/invite/$inviteId'
      path: '/invite/$inviteId'
      fullPath: '/invite/$inviteId'
      preLoaderRoute: typeof commonLayoutInviteInviteIdRouteImport
      parentRoute: typeof commonLayoutRoute
    }
    '/(common)/_layout/confirm-email/$emailId': {
      id: '/(common)/_layout/confirm-email/$emailId'
      path: '/confirm-email/$emailId'
      fullPath: '/confirm-email/$emailId'
      preLoaderRoute: typeof commonLayoutConfirmEmailEmailIdRouteImport
      parentRoute: typeof commonLayoutRoute
    }
    '/(app)/_layout/call/$callId': {
      id: '/(app)/_layout/call/$callId'
      path: '/call/$callId'
      fullPath: '/call/$callId'
      preLoaderRoute: typeof appLayoutCallCallIdRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/board/$boardId': {
      id: '/(app)/_layout/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof appLayoutBoardBoardIdRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/classrooms/$classroomId/': {
      id: '/(app)/_layout/classrooms/$classroomId/'
      path: '/classrooms/$classroomId'
      fullPath: '/classrooms/$classroomId/'
      preLoaderRoute: typeof appLayoutClassroomsClassroomIdIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/materials/$materialId/note/': {
      id: '/(app)/_layout/materials/$materialId/note/'
      path: '/materials/$materialId/note'
      fullPath: '/materials/$materialId/note/'
      preLoaderRoute: typeof appLayoutMaterialsMaterialIdNoteIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/materials/$materialId/board/': {
      id: '/(app)/_layout/materials/$materialId/board/'
      path: '/materials/$materialId/board'
      fullPath: '/materials/$materialId/board/'
      preLoaderRoute: typeof appLayoutMaterialsMaterialIdBoardIndexRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/classrooms/$classroomId/notes/$noteId': {
      id: '/(app)/_layout/classrooms/$classroomId/notes/$noteId'
      path: '/classrooms/$classroomId/notes/$noteId'
      fullPath: '/classrooms/$classroomId/notes/$noteId'
      preLoaderRoute: typeof appLayoutClassroomsClassroomIdNotesNoteIdRouteImport
      parentRoute: typeof appLayoutRoute
    }
    '/(app)/_layout/classrooms/$classroomId/boards/$boardId': {
      id: '/(app)/_layout/classrooms/$classroomId/boards/$boardId'
      path: '/classrooms/$classroomId/boards/$boardId'
      fullPath: '/classrooms/$classroomId/boards/$boardId'
      preLoaderRoute: typeof appLayoutClassroomsClassroomIdBoardsBoardIdRouteImport
      parentRoute: typeof appLayoutRoute
    }
  }
}

interface appLayoutRouteChildren {
  appLayoutIndexRoute: typeof appLayoutIndexRoute
  appLayoutBoardBoardIdRoute: typeof appLayoutBoardBoardIdRoute
  appLayoutCallCallIdRoute: typeof appLayoutCallCallIdRoute
  appLayoutCalendarIndexRoute: typeof appLayoutCalendarIndexRoute
  appLayoutCallIndexRoute: typeof appLayoutCallIndexRoute
  appLayoutClassroomsIndexRoute: typeof appLayoutClassroomsIndexRoute
  appLayoutMaterialsIndexRoute: typeof appLayoutMaterialsIndexRoute
  appLayoutPaymentsIndexRoute: typeof appLayoutPaymentsIndexRoute
  appLayoutClassroomsClassroomIdIndexRoute: typeof appLayoutClassroomsClassroomIdIndexRoute
  appLayoutClassroomsClassroomIdBoardsBoardIdRoute: typeof appLayoutClassroomsClassroomIdBoardsBoardIdRoute
  appLayoutClassroomsClassroomIdNotesNoteIdRoute: typeof appLayoutClassroomsClassroomIdNotesNoteIdRoute
  appLayoutMaterialsMaterialIdBoardIndexRoute: typeof appLayoutMaterialsMaterialIdBoardIndexRoute
  appLayoutMaterialsMaterialIdNoteIndexRoute: typeof appLayoutMaterialsMaterialIdNoteIndexRoute
}

const appLayoutRouteChildren: appLayoutRouteChildren = {
  appLayoutIndexRoute: appLayoutIndexRoute,
  appLayoutBoardBoardIdRoute: appLayoutBoardBoardIdRoute,
  appLayoutCallCallIdRoute: appLayoutCallCallIdRoute,
  appLayoutCalendarIndexRoute: appLayoutCalendarIndexRoute,
  appLayoutCallIndexRoute: appLayoutCallIndexRoute,
  appLayoutClassroomsIndexRoute: appLayoutClassroomsIndexRoute,
  appLayoutMaterialsIndexRoute: appLayoutMaterialsIndexRoute,
  appLayoutPaymentsIndexRoute: appLayoutPaymentsIndexRoute,
  appLayoutClassroomsClassroomIdIndexRoute:
    appLayoutClassroomsClassroomIdIndexRoute,
  appLayoutClassroomsClassroomIdBoardsBoardIdRoute:
    appLayoutClassroomsClassroomIdBoardsBoardIdRoute,
  appLayoutClassroomsClassroomIdNotesNoteIdRoute:
    appLayoutClassroomsClassroomIdNotesNoteIdRoute,
  appLayoutMaterialsMaterialIdBoardIndexRoute:
    appLayoutMaterialsMaterialIdBoardIndexRoute,
  appLayoutMaterialsMaterialIdNoteIndexRoute:
    appLayoutMaterialsMaterialIdNoteIndexRoute,
}

const appLayoutRouteWithChildren = appLayoutRoute._addFileChildren(
  appLayoutRouteChildren,
)

interface commonLayoutRouteChildren {
  commonLayoutConfirmEmailEmailIdRoute: typeof commonLayoutConfirmEmailEmailIdRoute
  commonLayoutInviteInviteIdRoute: typeof commonLayoutInviteInviteIdRoute
}

const commonLayoutRouteChildren: commonLayoutRouteChildren = {
  commonLayoutConfirmEmailEmailIdRoute: commonLayoutConfirmEmailEmailIdRoute,
  commonLayoutInviteInviteIdRoute: commonLayoutInviteInviteIdRoute,
}

const commonLayoutRouteWithChildren = commonLayoutRoute._addFileChildren(
  commonLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appLayoutRoute: appLayoutRouteWithChildren,
  commonLayoutRoute: commonLayoutRouteWithChildren,
  authResetPasswordResetTokenRoute: authResetPasswordResetTokenRoute,
  DeploymentsDeploymentIdEnableRoute: DeploymentsDeploymentIdEnableRoute,
  authResetPasswordIndexRoute: authResetPasswordIndexRoute,
  authSigninIndexRoute: authSigninIndexRoute,
  authSignupIndexRoute: authSignupIndexRoute,
  commonWelcomeEmailEmailIdRoute: commonWelcomeEmailEmailIdRoute,
  commonWelcomeRoleIndexRoute: commonWelcomeRoleIndexRoute,
  commonWelcomeSocialsIndexRoute: commonWelcomeSocialsIndexRoute,
  commonWelcomeUserIndexRoute: commonWelcomeUserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
