export type HistoricalSourceKey =
  | 'kiselev-arithmetic'
  | 'kiselev-geometry'
  | 'rybkin-planimetry'
  | 'rybkin-stereometry'
  | 'shaposhnikov-valtsov-algebra'
  | 'shaposhnikov-trigonometry';

export type HistoricalGeneratorKind =
  | 'ratio_sum'
  | 'reverse_fraction'
  | 'digit_number'
  | 'remainders'
  | 'rectangle_inverse'
  | 'motion_multi'
  | 'work_rate'
  | 'mixture_ratio'
  | 'linear_constructed'
  | 'system_constructed'
  | 'polynomial_factor'
  | 'function_line'
  | 'quadratic_roots'
  | 'quadratic_parameter'
  | 'rational_equation'
  | 'sequence_ap'
  | 'sequence_gp'
  | 'triangle_angle'
  | 'right_triangle'
  | 'similarity'
  | 'trapezoid'
  | 'circle_chords'
  | 'bisector'
  | 'coordinate_geometry'
  | 'trig_triangle'
  | 'trig_identity'
  | 'exponential'
  | 'logarithm'
  | 'stereometry_prism'
  | 'stereometry_pyramid'
  | 'vectors'
  | 'probability_combinatorial'
  | 'derivative_extremum'
  | 'tangent_parameter'
  | 'finance_growth'
  | 'number_theory'
  | 'integral_area'
  | 'mixed_parameter';

export type HistoricalArchetype = {
  id: string;
  groupId: string;
  variant: number;
  kind: HistoricalGeneratorKind;
  sourceKey: HistoricalSourceKey;
  grade: 5 | 6 | 7 | 8 | 9 | 10 | 11;
  difficulty: 3 | 4 | 5;
  topicId: string;
  topic: string;
  subtopic: string;
  skills: string[];
  tags: string[];
  aliases: string[];
};

type Group = Omit<HistoricalArchetype, 'id' | 'variant' | 'difficulty'> & {
  variants: number;
  difficulties: readonly (3 | 4 | 5)[];
};

const groups: Group[] = [
  // 5 класс — арифметическая традиция Киселёва: отношения, дроби, задачи на числа и величины.
  {
    groupId: 'g5-ratio-sum',
    kind: 'ratio_sum',
    sourceKey: 'kiselev-arithmetic',
    grade: 5,
    variants: 4,
    difficulties: [3, 4, 5],
    topicId: 'arithmetic.relations_three',
    topic: 'Натуральные числа',
    subtopic: 'Связанные величины и сумма',
    skills: ['отношения величин', 'арифметическое моделирование'],
    tags: ['отношения', 'сумма', 'текстовая задача'],
    aliases: ['части и сумма', 'связанные величины'],
  },
  {
    groupId: 'g5-reverse-fraction',
    kind: 'reverse_fraction',
    sourceKey: 'kiselev-arithmetic',
    grade: 5,
    variants: 4,
    difficulties: [3, 4, 5],
    topicId: 'fractions.reverse_multi',
    topic: 'Обыкновенные дроби',
    subtopic: 'Обратная многошаговая задача',
    skills: ['дробь от числа', 'восстановление целого', 'последовательные действия'],
    tags: ['дроби', 'обратная задача'],
    aliases: ['найти целое по части', 'дроби несколько действий'],
  },
  {
    groupId: 'g5-digit-number',
    kind: 'digit_number',
    sourceKey: 'kiselev-arithmetic',
    grade: 5,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'numbers.digits_reverse',
    topic: 'Натуральные числа',
    subtopic: 'Цифры и перестановка',
    skills: ['разрядный состав числа', 'логические рассуждения'],
    tags: ['цифры', 'двузначное число'],
    aliases: ['перестановка цифр', 'задача на цифры'],
  },
  {
    groupId: 'g5-remainders',
    kind: 'remainders',
    sourceKey: 'kiselev-arithmetic',
    grade: 5,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'numbers.two_conditions',
    topic: 'Натуральные числа',
    subtopic: 'Число по условиям делимости',
    skills: ['остаток от деления', 'перебор кратных'],
    tags: ['делимость', 'остатки'],
    aliases: ['число по остаткам', 'кратность'],
  },
  {
    groupId: 'g5-rectangle-inverse',
    kind: 'rectangle_inverse',
    sourceKey: 'kiselev-geometry',
    grade: 5,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'geometry.rectangle_inverse',
    topic: 'Геометрические величины',
    subtopic: 'Прямоугольник по косвенным данным',
    skills: ['периметр прямоугольника', 'площадь прямоугольника', 'восстановление сторон'],
    tags: ['прямоугольник', 'периметр', 'площадь'],
    aliases: ['найти стороны прямоугольника'],
  },
  {
    groupId: 'g5-motion',
    kind: 'motion_multi',
    sourceKey: 'kiselev-arithmetic',
    grade: 5,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'word.motion',
    topic: 'Текстовые задачи',
    subtopic: 'Движение в несколько этапов',
    skills: ['скорость время расстояние', 'арифметическая модель'],
    tags: ['движение', 'скорость'],
    aliases: ['задача на движение'],
  },
  {
    groupId: 'g5-work',
    kind: 'work_rate',
    sourceKey: 'kiselev-arithmetic',
    grade: 5,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'word.work',
    topic: 'Текстовые задачи',
    subtopic: 'Совместная работа',
    skills: ['доля работы', 'совместная производительность'],
    tags: ['работа', 'производительность'],
    aliases: ['задача на работу'],
  },
  {
    groupId: 'g5-number-theory',
    kind: 'number_theory',
    sourceKey: 'kiselev-arithmetic',
    grade: 5,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'numbers.common_multiple_search',
    topic: 'Натуральные числа',
    subtopic: 'Делимость и общие кратные',
    skills: ['НОК', 'делимость', 'поиск числа'],
    tags: ['делимость', 'нок'],
    aliases: ['общее кратное'],
  },

  // 6 класс.
  {
    groupId: 'g6-ratio-sum',
    kind: 'ratio_sum',
    sourceKey: 'kiselev-arithmetic',
    grade: 6,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'ratios.three_parts',
    topic: 'Отношения и пропорции',
    subtopic: 'Связанные отношения трёх величин',
    skills: ['отношение', 'пропорция', 'деление на части'],
    tags: ['отношения', 'пропорции'],
    aliases: ['деление в отношении'],
  },
  {
    groupId: 'g6-reverse-fraction',
    kind: 'reverse_fraction',
    sourceKey: 'kiselev-arithmetic',
    grade: 6,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'percents.reverse_fraction',
    topic: 'Проценты и дроби',
    subtopic: 'Обратная многошаговая задача',
    skills: ['проценты', 'дроби', 'восстановление исходной величины'],
    tags: ['проценты', 'дроби'],
    aliases: ['обратная задача на проценты'],
  },
  {
    groupId: 'g6-remainders',
    kind: 'remainders',
    sourceKey: 'kiselev-arithmetic',
    grade: 6,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'numbers.remainders',
    topic: 'Делимость',
    subtopic: 'Число по нескольким остаткам',
    skills: ['остатки', 'делимость', 'поиск закономерности'],
    tags: ['остатки', 'делимость'],
    aliases: ['сравнения по модулю'],
  },
  {
    groupId: 'g6-motion',
    kind: 'motion_multi',
    sourceKey: 'kiselev-arithmetic',
    grade: 6,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'word.motion',
    topic: 'Текстовые задачи',
    subtopic: 'Движение и относительная скорость',
    skills: ['относительная скорость', 'скорость время расстояние'],
    tags: ['движение'],
    aliases: ['встречное движение', 'догонка'],
  },
  {
    groupId: 'g6-work',
    kind: 'work_rate',
    sourceKey: 'kiselev-arithmetic',
    grade: 6,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'word.work',
    topic: 'Текстовые задачи',
    subtopic: 'Совместная производительность',
    skills: ['доля работы', 'производительность'],
    tags: ['работа', 'производительность'],
    aliases: ['совместная работа'],
  },
  {
    groupId: 'g6-mixture',
    kind: 'mixture_ratio',
    sourceKey: 'kiselev-arithmetic',
    grade: 6,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'ratios.transfer',
    topic: 'Отношения и пропорции',
    subtopic: 'Изменение отношения после добавления',
    skills: ['отношение', 'пропорция', 'изменение состава'],
    tags: ['отношения', 'смеси'],
    aliases: ['задача на смесь', 'изменение отношения'],
  },
  {
    groupId: 'g6-linear',
    kind: 'linear_constructed',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 6,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'equations.brackets',
    topic: 'Уравнения',
    subtopic: 'Уравнения со скобками и дробями',
    skills: ['линейное уравнение', 'раскрытие скобок', 'перенос слагаемых'],
    tags: ['уравнения'],
    aliases: ['линейное уравнение со скобками'],
  },
  {
    groupId: 'g6-coordinate',
    kind: 'coordinate_geometry',
    sourceKey: 'kiselev-geometry',
    grade: 6,
    variants: 2,
    difficulties: [3, 4],
    topicId: 'coordinates.plane',
    topic: 'Координаты',
    subtopic: 'Расстояние и середина отрезка',
    skills: ['координатная плоскость', 'расстояние между точками'],
    tags: ['координаты'],
    aliases: ['точки на координатной плоскости'],
  },
  {
    groupId: 'g6-number-theory',
    kind: 'number_theory',
    sourceKey: 'kiselev-arithmetic',
    grade: 6,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'numbers.gcd_lcm',
    topic: 'Делимость',
    subtopic: 'НОД, НОК и условия делимости',
    skills: ['НОД', 'НОК', 'разложение на множители'],
    tags: ['нод', 'нок', 'делимость'],
    aliases: ['наибольший общий делитель', 'наименьшее общее кратное'],
  },

  // 7 класс.
  {
    groupId: 'g7-linear',
    kind: 'linear_constructed',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 7,
    variants: 4,
    difficulties: [3, 4, 5],
    topicId: 'equations.double_brackets',
    topic: 'Линейные уравнения',
    subtopic: 'Многошаговые линейные уравнения',
    skills: ['линейное уравнение', 'раскрытие скобок', 'приведение подобных'],
    tags: ['уравнения'],
    aliases: ['сложное линейное уравнение'],
  },
  {
    groupId: 'g7-system',
    kind: 'system_constructed',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 7,
    variants: 4,
    difficulties: [3, 4, 5],
    topicId: 'algebra.systems',
    topic: 'Системы уравнений',
    subtopic: 'Система двух линейных уравнений',
    skills: ['система уравнений', 'подстановка', 'сложение уравнений'],
    tags: ['системы'],
    aliases: ['система двух уравнений'],
  },
  {
    groupId: 'g7-polynomial',
    kind: 'polynomial_factor',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 7,
    variants: 4,
    difficulties: [3, 4, 5],
    topicId: 'algebra.factorization',
    topic: 'Многочлены',
    subtopic: 'Разложение на множители и тождества',
    skills: ['формулы сокращённого умножения', 'разложение на множители'],
    tags: ['многочлены', 'разложение'],
    aliases: ['фсу', 'вынесение множителя'],
  },
  {
    groupId: 'g7-lines',
    kind: 'function_line',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 7,
    variants: 4,
    difficulties: [3, 4, 5],
    topicId: 'functions.lines_intersection',
    topic: 'Линейная функция',
    subtopic: 'Пересечение и параметры прямых',
    skills: ['линейная функция', 'пересечение графиков', 'коэффициенты прямой'],
    tags: ['функции', 'графики'],
    aliases: ['графики прямых'],
  },
  {
    groupId: 'g7-motion',
    kind: 'motion_multi',
    sourceKey: 'kiselev-arithmetic',
    grade: 7,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'systems.word_problem',
    topic: 'Системы линейных уравнений',
    subtopic: 'Движение и система уравнений',
    skills: ['текстовая модель', 'система уравнений'],
    tags: ['движение', 'системы'],
    aliases: ['задача на движение системой'],
  },
  {
    groupId: 'g7-mixture',
    kind: 'mixture_ratio',
    sourceKey: 'kiselev-arithmetic',
    grade: 7,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'systems.word_problem',
    topic: 'Системы линейных уравнений',
    subtopic: 'Состав смеси и отношения',
    skills: ['система уравнений', 'отношение величин'],
    tags: ['смеси', 'системы'],
    aliases: ['задача на смесь'],
  },
  {
    groupId: 'g7-triangle-angle',
    kind: 'triangle_angle',
    sourceKey: 'kiselev-geometry',
    grade: 7,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'geometry.angle_chain',
    topic: 'Геометрия',
    subtopic: 'Цепочки углов в треугольнике',
    skills: ['сумма углов треугольника', 'внешний угол', 'биссектриса'],
    tags: ['треугольник', 'углы'],
    aliases: ['задача на углы'],
  },
  {
    groupId: 'g7-coordinate',
    kind: 'coordinate_geometry',
    sourceKey: 'kiselev-geometry',
    grade: 7,
    variants: 2,
    difficulties: [3, 4],
    topicId: 'functions.linear',
    topic: 'Линейная функция',
    subtopic: 'Координаты точек и график',
    skills: ['координаты', 'линейная функция'],
    tags: ['координаты', 'график'],
    aliases: ['точка на прямой'],
  },
  {
    groupId: 'g7-probability',
    kind: 'probability_combinatorial',
    sourceKey: 'kiselev-arithmetic',
    grade: 7,
    variants: 2,
    difficulties: [3, 4],
    topicId: 'probability.classical',
    topic: 'Вероятность и статистика',
    subtopic: 'Классическая вероятность',
    skills: ['равновозможные исходы', 'подсчёт исходов'],
    tags: ['вероятность'],
    aliases: ['классическая вероятность'],
  },
  {
    groupId: 'g7-number-theory',
    kind: 'number_theory',
    sourceKey: 'kiselev-arithmetic',
    grade: 7,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'numbers.divisibility',
    topic: 'Числа и делимость',
    subtopic: 'Делимость алгебраических выражений',
    skills: ['делимость', 'остатки'],
    tags: ['делимость'],
    aliases: ['задачи на делимость'],
  },

  // 8 класс.
  {
    groupId: 'g8-quadratic-roots',
    kind: 'quadratic_roots',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 8,
    variants: 4,
    difficulties: [3, 4, 5],
    topicId: 'quadratics.vieta',
    topic: 'Квадратные уравнения',
    subtopic: 'Корни и теорема Виета',
    skills: ['теорема Виета', 'корни квадратного уравнения'],
    tags: ['квадратные уравнения', 'виет'],
    aliases: ['теорема виета'],
  },
  {
    groupId: 'g8-quadratic-parameter',
    kind: 'quadratic_parameter',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 8,
    variants: 4,
    difficulties: [3, 4, 5],
    topicId: 'quadratics.parameter_discriminant',
    topic: 'Квадратные уравнения',
    subtopic: 'Параметр и свойства корней',
    skills: ['дискриминант', 'теорема Виета', 'параметр'],
    tags: ['квадратные уравнения', 'параметр'],
    aliases: ['параметр в квадратном уравнении'],
  },
  {
    groupId: 'g8-rational',
    kind: 'rational_equation',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 8,
    variants: 4,
    difficulties: [3, 4, 5],
    topicId: 'rational.rational_equation',
    topic: 'Рациональные выражения',
    subtopic: 'Дробно-рациональные уравнения',
    skills: ['ОДЗ', 'рациональное уравнение'],
    tags: ['рациональные уравнения'],
    aliases: ['дробное уравнение'],
  },
  {
    groupId: 'g8-similarity',
    kind: 'similarity',
    sourceKey: 'rybkin-planimetry',
    grade: 8,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'geometry.similarity',
    topic: 'Геометрия',
    subtopic: 'Подобие треугольников',
    skills: ['подобие треугольников', 'пропорциональные стороны'],
    tags: ['геометрия', 'подобие'],
    aliases: ['подобные треугольники'],
  },
  {
    groupId: 'g8-right-triangle',
    kind: 'right_triangle',
    sourceKey: 'rybkin-planimetry',
    grade: 8,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'geometry.right_triangle_multi',
    topic: 'Геометрия',
    subtopic: 'Прямоугольный треугольник',
    skills: ['теорема Пифагора', 'площадь треугольника'],
    tags: ['геометрия', 'пифагор'],
    aliases: ['прямоугольный треугольник'],
  },
  {
    groupId: 'g8-trapezoid',
    kind: 'trapezoid',
    sourceKey: 'rybkin-planimetry',
    grade: 8,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'geometry.trapezoid_height',
    topic: 'Геометрия',
    subtopic: 'Равнобедренная трапеция',
    skills: ['теорема Пифагора', 'площадь трапеции'],
    tags: ['трапеция', 'геометрия'],
    aliases: ['равнобедренная трапеция'],
  },
  {
    groupId: 'g8-chords',
    kind: 'circle_chords',
    sourceKey: 'rybkin-planimetry',
    grade: 8,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'geometry.chords_product',
    topic: 'Геометрия',
    subtopic: 'Хорды и произведения отрезков',
    skills: ['пересекающиеся хорды', 'пропорции'],
    tags: ['окружность', 'хорды'],
    aliases: ['теорема о хордах'],
  },
  {
    groupId: 'g8-bisector',
    kind: 'bisector',
    sourceKey: 'rybkin-planimetry',
    grade: 8,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'geometry.bisector',
    topic: 'Геометрия',
    subtopic: 'Биссектриса треугольника',
    skills: ['теорема о биссектрисе', 'отношение сторон'],
    tags: ['биссектриса', 'треугольник'],
    aliases: ['теорема о биссектрисе'],
  },
  {
    groupId: 'g8-probability',
    kind: 'probability_combinatorial',
    sourceKey: 'kiselev-arithmetic',
    grade: 8,
    variants: 2,
    difficulties: [3, 4],
    topicId: 'probability.dependent',
    topic: 'Вероятность и статистика',
    subtopic: 'Последовательный выбор без возвращения',
    skills: ['условная вероятность', 'дроби'],
    tags: ['вероятность'],
    aliases: ['выбор без возвращения'],
  },
  {
    groupId: 'g8-function',
    kind: 'function_line',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 8,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'functions.quadratic',
    topic: 'Функции',
    subtopic: 'Связь графиков и уравнений',
    skills: ['график функции', 'решение уравнений'],
    tags: ['функции', 'графики'],
    aliases: ['пересечение графиков'],
  },
  {
    groupId: 'g8-coordinate',
    kind: 'coordinate_geometry',
    sourceKey: 'kiselev-geometry',
    grade: 8,
    variants: 2,
    difficulties: [3, 4],
    topicId: 'geometry.coordinate',
    topic: 'Геометрия',
    subtopic: 'Координаты и расстояния',
    skills: ['координаты', 'теорема Пифагора'],
    tags: ['координаты', 'геометрия'],
    aliases: ['расстояние по координатам'],
  },

  // 9 класс.
  {
    groupId: 'g9-quadratic-parameter',
    kind: 'quadratic_parameter',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 9,
    variants: 4,
    difficulties: [3, 4, 5],
    topicId: 'quadratics.parameter_roots_relation',
    topic: 'Квадратные уравнения',
    subtopic: 'Параметр по связи между корнями',
    skills: ['теорема Виета', 'параметр', 'дискриминант'],
    tags: ['параметр', 'квадратное уравнение'],
    aliases: ['связь корней'],
  },
  {
    groupId: 'g9-rational',
    kind: 'rational_equation',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 9,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'algebra.rational_equations',
    topic: 'Алгебра',
    subtopic: 'Рациональные уравнения',
    skills: ['ОДЗ', 'рациональное уравнение'],
    tags: ['уравнения'],
    aliases: ['дробно рациональное уравнение'],
  },
  {
    groupId: 'g9-ap',
    kind: 'sequence_ap',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 9,
    variants: 4,
    difficulties: [3, 4, 5],
    topicId: 'sequences.arithmetic',
    topic: 'Числовые последовательности',
    subtopic: 'Арифметическая прогрессия',
    skills: ['арифметическая прогрессия', 'формула n-го члена', 'сумма прогрессии'],
    tags: ['прогрессии'],
    aliases: ['арифметическая прогрессия'],
  },
  {
    groupId: 'g9-gp',
    kind: 'sequence_gp',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 9,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'sequences.geometric',
    topic: 'Числовые последовательности',
    subtopic: 'Геометрическая прогрессия',
    skills: ['геометрическая прогрессия', 'формула n-го члена'],
    tags: ['прогрессии'],
    aliases: ['геометрическая прогрессия'],
  },
  {
    groupId: 'g9-triangle-angle',
    kind: 'triangle_angle',
    sourceKey: 'rybkin-planimetry',
    grade: 9,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'geometry.circle_angles',
    topic: 'Геометрия',
    subtopic: 'Углы и дополнительные построения',
    skills: ['углы треугольника', 'биссектриса', 'внешний угол'],
    tags: ['геометрия', 'углы'],
    aliases: ['планиметрия углы'],
  },
  {
    groupId: 'g9-right-triangle',
    kind: 'right_triangle',
    sourceKey: 'rybkin-planimetry',
    grade: 9,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'geometry.right_triangle_altitude',
    topic: 'Геометрия',
    subtopic: 'Метрические соотношения в прямоугольном треугольнике',
    skills: ['теорема Пифагора', 'высота к гипотенузе'],
    tags: ['планиметрия', 'прямоугольный треугольник'],
    aliases: ['высота к гипотенузе'],
  },
  {
    groupId: 'g9-similarity',
    kind: 'similarity',
    sourceKey: 'rybkin-planimetry',
    grade: 9,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'geometry.similarity_area',
    topic: 'Геометрия',
    subtopic: 'Подобие и площади',
    skills: ['подобие', 'отношение площадей'],
    tags: ['планиметрия', 'подобие'],
    aliases: ['площади подобных фигур'],
  },
  {
    groupId: 'g9-trapezoid',
    kind: 'trapezoid',
    sourceKey: 'rybkin-planimetry',
    grade: 9,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'geometry.trapezoid_diagonal',
    topic: 'Геометрия',
    subtopic: 'Трапеция и метрические связи',
    skills: ['трапеция', 'теорема Пифагора', 'площадь'],
    tags: ['трапеция', 'планиметрия'],
    aliases: ['сложная трапеция'],
  },
  {
    groupId: 'g9-chords',
    kind: 'circle_chords',
    sourceKey: 'rybkin-planimetry',
    grade: 9,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'geometry.chords_product',
    topic: 'Геометрия',
    subtopic: 'Пересекающиеся хорды',
    skills: ['теорема о хордах', 'произведение отрезков'],
    tags: ['окружность', 'хорды'],
    aliases: ['пересекающиеся хорды'],
  },
  {
    groupId: 'g9-bisector',
    kind: 'bisector',
    sourceKey: 'rybkin-planimetry',
    grade: 9,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'geometry.bisector',
    topic: 'Геометрия',
    subtopic: 'Биссектриса и отношения отрезков',
    skills: ['теорема о биссектрисе', 'отношение сторон'],
    tags: ['биссектриса', 'планиметрия'],
    aliases: ['биссектриса треугольника'],
  },
  {
    groupId: 'g9-coordinate',
    kind: 'coordinate_geometry',
    sourceKey: 'kiselev-geometry',
    grade: 9,
    variants: 1,
    difficulties: [4],
    topicId: 'geometry.coordinate_midpoint',
    topic: 'Координатная геометрия',
    subtopic: 'Расстояние, середина и площадь',
    skills: ['координаты', 'расстояние', 'середина отрезка'],
    tags: ['координаты'],
    aliases: ['координатная геометрия'],
  },
  {
    groupId: 'g9-trig-triangle',
    kind: 'trig_triangle',
    sourceKey: 'shaposhnikov-trigonometry',
    grade: 9,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'geometry.trigonometry',
    topic: 'Геометрия',
    subtopic: 'Тригонометрия в прямоугольном треугольнике',
    skills: ['синус', 'косинус', 'тангенс'],
    tags: ['тригонометрия', 'планиметрия'],
    aliases: ['синус косинус в треугольнике'],
  },
  {
    groupId: 'g9-probability',
    kind: 'probability_combinatorial',
    sourceKey: 'kiselev-arithmetic',
    grade: 9,
    variants: 1,
    difficulties: [4],
    topicId: 'probability.dependent',
    topic: 'Вероятность и статистика',
    subtopic: 'Комбинаторная вероятность',
    skills: ['подсчёт исходов', 'вероятность'],
    tags: ['вероятность'],
    aliases: ['комбинаторная вероятность'],
  },
  {
    groupId: 'g9-number-theory',
    kind: 'number_theory',
    sourceKey: 'kiselev-arithmetic',
    grade: 9,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'number_theory.divisibility',
    topic: 'Числа и делимость',
    subtopic: 'Делимость и остатки',
    skills: ['делимость', 'остатки', 'НОК'],
    tags: ['делимость'],
    aliases: ['теория чисел'],
  },

  // 10 класс.
  {
    groupId: 'g10-trig-triangle',
    kind: 'trig_triangle',
    sourceKey: 'shaposhnikov-trigonometry',
    grade: 10,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'trigonometry.expression',
    topic: 'Тригонометрия',
    subtopic: 'Тригонометрические отношения',
    skills: ['синус', 'косинус', 'тангенс', 'тождество'],
    tags: ['тригонометрия'],
    aliases: ['тригонометрические значения'],
  },
  {
    groupId: 'g10-trig-identity',
    kind: 'trig_identity',
    sourceKey: 'shaposhnikov-trigonometry',
    grade: 10,
    variants: 4,
    difficulties: [3, 4, 5],
    topicId: 'trigonometry.sum_identity',
    topic: 'Тригонометрия',
    subtopic: 'Тождества и преобразования',
    skills: ['основное тригонометрическое тождество', 'формулы двойного угла'],
    tags: ['тригонометрия', 'тождество'],
    aliases: ['тригонометрические преобразования'],
  },
  {
    groupId: 'g10-exponential',
    kind: 'exponential',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 10,
    variants: 4,
    difficulties: [3, 4, 5],
    topicId: 'equations.exponential_substitution',
    topic: 'Показательные уравнения',
    subtopic: 'Показательные уравнения и замена переменной',
    skills: ['показательное уравнение', 'замена переменной'],
    tags: ['показательные уравнения'],
    aliases: ['экспоненциальное уравнение'],
  },
  {
    groupId: 'g10-logarithm',
    kind: 'logarithm',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 10,
    variants: 4,
    difficulties: [3, 4, 5],
    topicId: 'logarithms.properties',
    topic: 'Логарифмы',
    subtopic: 'Логарифмические преобразования и уравнения',
    skills: ['свойства логарифмов', 'логарифмическое уравнение'],
    tags: ['логарифмы'],
    aliases: ['логарифмическое уравнение'],
  },
  {
    groupId: 'g10-prism',
    kind: 'stereometry_prism',
    sourceKey: 'rybkin-stereometry',
    grade: 10,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'stereometry.prism_volume',
    topic: 'Стереометрия',
    subtopic: 'Призма и параллелепипед',
    skills: ['объём призмы', 'пространственная диагональ', 'площадь поверхности'],
    tags: ['стереометрия', 'призма'],
    aliases: ['прямоугольный параллелепипед'],
  },
  {
    groupId: 'g10-pyramid',
    kind: 'stereometry_pyramid',
    sourceKey: 'rybkin-stereometry',
    grade: 10,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'stereometry.pyramid_volume',
    topic: 'Стереометрия',
    subtopic: 'Пирамида',
    skills: ['объём пирамиды', 'высота', 'площадь основания'],
    tags: ['стереометрия', 'пирамида'],
    aliases: ['квадратная пирамида'],
  },
  {
    groupId: 'g10-vectors',
    kind: 'vectors',
    sourceKey: 'kiselev-geometry',
    grade: 10,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'vectors.dot_product',
    topic: 'Векторы',
    subtopic: 'Скалярное произведение и координаты',
    skills: ['скалярное произведение', 'перпендикулярность векторов'],
    tags: ['векторы'],
    aliases: ['скалярное произведение'],
  },
  {
    groupId: 'g10-probability',
    kind: 'probability_combinatorial',
    sourceKey: 'kiselev-arithmetic',
    grade: 10,
    variants: 2,
    difficulties: [3, 4],
    topicId: 'probability.independent',
    topic: 'Вероятность и комбинаторика',
    subtopic: 'Комбинаторные модели вероятности',
    skills: ['комбинаторика', 'вероятность'],
    tags: ['вероятность', 'комбинаторика'],
    aliases: ['выбор без возвращения'],
  },
  {
    groupId: 'g10-system',
    kind: 'system_constructed',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 10,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'equations.systems',
    topic: 'Уравнения и системы',
    subtopic: 'Системы с дополнительным условием',
    skills: ['система уравнений', 'алгебраические преобразования'],
    tags: ['системы'],
    aliases: ['система уравнений'],
  },
  {
    groupId: 'g10-number-theory',
    kind: 'number_theory',
    sourceKey: 'kiselev-arithmetic',
    grade: 10,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'number_theory.divisibility',
    topic: 'Числа и делимость',
    subtopic: 'Условия на остатки и делимость',
    skills: ['остатки', 'делимость'],
    tags: ['делимость'],
    aliases: ['теория чисел'],
  },

  // 11 класс.
  {
    groupId: 'g11-derivative',
    kind: 'derivative_extremum',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 11,
    variants: 4,
    difficulties: [3, 4, 5],
    topicId: 'calculus.extremum_interval',
    topic: 'Производная',
    subtopic: 'Экстремумы и значения на отрезке',
    skills: ['производная', 'критические точки', 'экстремум'],
    tags: ['производная', 'экстремум'],
    aliases: ['максимум минимум функции'],
  },
  {
    groupId: 'g11-tangent',
    kind: 'tangent_parameter',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 11,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'parameters.tangent_parameter',
    topic: 'Производная и параметр',
    subtopic: 'Касательная и параметр',
    skills: ['производная', 'касательная', 'параметр'],
    tags: ['касательная', 'параметр'],
    aliases: ['уравнение касательной'],
  },
  {
    groupId: 'g11-finance',
    kind: 'finance_growth',
    sourceKey: 'kiselev-arithmetic',
    grade: 11,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'finance.compound_growth',
    topic: 'Финансовая математика',
    subtopic: 'Последовательные процентные изменения',
    skills: ['сложный процент', 'обратный расчёт'],
    tags: ['финансы', 'проценты'],
    aliases: ['сложный процент'],
  },
  {
    groupId: 'g11-number-theory',
    kind: 'number_theory',
    sourceKey: 'kiselev-arithmetic',
    grade: 11,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'number_theory.congruence_search',
    topic: 'Числа и делимость',
    subtopic: 'Совместные условия на остатки',
    skills: ['остатки', 'делимость', 'НОК'],
    tags: ['теория чисел', 'остатки'],
    aliases: ['сравнения по модулю'],
  },
  {
    groupId: 'g11-integral',
    kind: 'integral_area',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 11,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'calculus.integral',
    topic: 'Начала математического анализа',
    subtopic: 'Определённый интеграл и площадь',
    skills: ['первообразная', 'определённый интеграл', 'площадь'],
    tags: ['интеграл'],
    aliases: ['определенный интеграл'],
  },
  {
    groupId: 'g11-parameter',
    kind: 'mixed_parameter',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 11,
    variants: 3,
    difficulties: [3, 4, 5],
    topicId: 'parameters.quadratic_double_root',
    topic: 'Уравнения с параметром',
    subtopic: 'Параметр и корни уравнения',
    skills: ['параметр', 'дискриминант', 'теорема Виета'],
    tags: ['параметр'],
    aliases: ['задача с параметром'],
  },
  {
    groupId: 'g11-exponential',
    kind: 'exponential',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 11,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'exponential.inequalities',
    topic: 'Показательная функция',
    subtopic: 'Показательные уравнения и системы',
    skills: ['показательная функция', 'замена переменной'],
    tags: ['показательная функция'],
    aliases: ['показательные уравнения'],
  },
  {
    groupId: 'g11-logarithm',
    kind: 'logarithm',
    sourceKey: 'shaposhnikov-valtsov-algebra',
    grade: 11,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'logarithms.equations',
    topic: 'Логарифмы',
    subtopic: 'Логарифмические уравнения',
    skills: ['логарифм', 'ОДЗ', 'преобразования'],
    tags: ['логарифмы'],
    aliases: ['логарифмические уравнения'],
  },
  {
    groupId: 'g11-prism',
    kind: 'stereometry_prism',
    sourceKey: 'rybkin-stereometry',
    grade: 11,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'stereometry.prism_volume',
    topic: 'Стереометрия',
    subtopic: 'Призма: объём и метрические связи',
    skills: ['объём', 'диагональ', 'площадь поверхности'],
    tags: ['стереометрия', 'призма'],
    aliases: ['призма'],
  },
  {
    groupId: 'g11-pyramid',
    kind: 'stereometry_pyramid',
    sourceKey: 'rybkin-stereometry',
    grade: 11,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'stereometry.pyramid_volume',
    topic: 'Стереометрия',
    subtopic: 'Пирамида: объём и сечения',
    skills: ['объём пирамиды', 'высота', 'площадь основания'],
    tags: ['стереометрия', 'пирамида'],
    aliases: ['пирамида'],
  },
  {
    groupId: 'g11-circle',
    kind: 'circle_chords',
    sourceKey: 'rybkin-planimetry',
    grade: 11,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'geometry.circle_power',
    topic: 'Планиметрия',
    subtopic: 'Степень точки и хорды',
    skills: ['степень точки', 'хорды', 'пропорции'],
    tags: ['окружность', 'планиметрия'],
    aliases: ['степень точки'],
  },
  {
    groupId: 'g11-trig',
    kind: 'trig_identity',
    sourceKey: 'shaposhnikov-trigonometry',
    grade: 11,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'trigonometry.identity',
    topic: 'Тригонометрия',
    subtopic: 'Комбинированные преобразования',
    skills: ['тригонометрические тождества', 'двойной угол'],
    tags: ['тригонометрия'],
    aliases: ['тригонометрические преобразования'],
  },
  {
    groupId: 'g11-probability',
    kind: 'probability_combinatorial',
    sourceKey: 'kiselev-arithmetic',
    grade: 11,
    variants: 2,
    difficulties: [4, 5],
    topicId: 'probability.bernoulli',
    topic: 'Вероятность и статистика',
    subtopic: 'Составные вероятностные модели',
    skills: ['комбинаторика', 'вероятность', 'дроби'],
    tags: ['вероятность'],
    aliases: ['составная вероятность'],
  },
];

export const historicalArchetypes: HistoricalArchetype[] = groups.flatMap((group) =>
  Array.from({ length: group.variants }, (_, index) => ({
    id: `hist-${group.groupId}-v${String(index + 1).padStart(2, '0')}`,
    groupId: group.groupId,
    variant: index + 1,
    kind: group.kind,
    sourceKey: group.sourceKey,
    grade: group.grade,
    difficulty: group.difficulties[index % group.difficulties.length]!,
    topicId: group.topicId,
    topic: group.topic,
    subtopic: group.subtopic,
    skills: [...group.skills],
    tags: [...group.tags],
    aliases: [...group.aliases],
  })),
);
