import { MaterialPropsT } from './types';

export const mockMaterials: MaterialPropsT[] = [
  {
    idMaterial: '1',
    nameMaterial: 'Название 1',
    updatedAt: '2024-01-01',
    idUser: 1,
    nameUser: 'Анна Смирнова',
    roleUser: 'teacher',
  },
  {
    idMaterial: '2',
    nameMaterial: 'Название 2',
    updatedAt: '2024-01-01',
    idUser: 2,
    nameUser: 'Максим Иванов',
    roleUser: 'student',
  },
  {
    idMaterial: '3',
    nameMaterial: 'Название 3',
    updatedAt: '2024-01-01',
    idUser: 3,
    nameUser: 'Елизавета Петрова',
    roleUser: 'student',
  },
  {
    idMaterial: '4',
    nameMaterial: 'Название 4',
    updatedAt: '2024-01-01',
    idUser: 4,
    nameUser: 'Дмитрий Кузнецов',
    roleUser: 'teacher',
  },
  {
    idMaterial: '5',
    nameMaterial: 'Название 5',
    updatedAt: '2024-01-01',
    idUser: 5,
    nameUser: 'Андрей Соколов',
    roleUser: 'student',
  },
  {
    idMaterial: '6',
    nameMaterial: 'Название 6',
    updatedAt: '2024-01-01',
    idUser: 6,
    nameUser: 'Кирилл Лебедев',
    roleUser: 'teacher',
  },
  {
    idMaterial: '7',
    nameMaterial: 'Название 7',
    updatedAt: '2024-01-01',
    idUser: 7,
    nameUser: 'Наталья Орлова',
    roleUser: 'student',
  },
  {
    idMaterial: '8',
    nameMaterial: 'Название 8',
    updatedAt: '2024-01-01',
    idUser: 8,
    nameUser: 'English Group',
    roleUser: 'student',
  },
  {
    idMaterial: '9',
    nameMaterial: 'Название 9',
    updatedAt: '2024-01-01',
    idUser: 9,
    nameUser: 'Удаленный пользователь',
    roleUser: 'teacher',
  },
];
