name: On Push To Main (Production)

on:
  push:
    branches:
      - main

jobs:
  main:
    uses: ./.github/workflows/main.yml
    with:
      base_deployment_path: ~/xieffect-core/static
      deployment_name: main
      github_environment_name: xi-production
    secrets: inherit

  report_to_webhook:
    needs:
      - main
    if: always()
    environment: xi-production
    runs-on: ubuntu-latest

    steps:
      - name: Report about deployment success
        if: needs.main.result == 'success'
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: |-
            :flag_bg: Service xi.tutor successfully deployed
            Commit: `${{ github.sha }}`

      - name: Report failure to discord
        if: failure()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: |-
            :x: [Service xi.tutor failed to deploy](<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>)
            Commit: `${{ github.sha }}`
