name: Development

on:
  pull_request:
  workflow_dispatch:

env:
  project_name: xi.tutor
  app_name: xi.web

jobs:
  namer:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch & deployment name
        id: get_names
        run: |-
          branch_name=${{ github.event.pull_request.head.ref }}
          echo "branch_name=${branch_name}"
          echo "branch_name=${branch_name}" >> $GITHUB_OUTPUT

          deployment_name="${branch_name////-}"
          echo "deployment_name=${deployment_name}"
          echo "deployment_name=${deployment_name}" >> $GITHUB_OUTPUT

    outputs:
      branch_name: ${{ steps.get_names.outputs.branch_name }}
      deployment_name: ${{ steps.get_names.outputs.deployment_name }}

  analyze_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Filter paths
        uses: dorny/paths-filter@v2
        id: path_filter
        with:
          filters: .github/files.yml

    outputs:
      xi_web_files: ${{ steps.path_filter.outputs.xi_web_files }}
      lintable_files: ${{ steps.path_filter.outputs.lintable_files }}

  lint:
    needs: analyze_files
    if: needs.analyze_files.outputs.lintable_files == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install pnpm (version from package.json)
        uses: pnpm/action-setup@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4.3.0
        with:
          node-version-file: package.json
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install dependencies
        id: install
        run: pnpm install

      - name: Run format checker
        run: pnpm run format-check

      - name: Run linter
        if: success() || (failure() && (steps.install.conclusion == 'success'))
        run: pnpm run lint

  build_xi_web:
    needs:
      - namer
      - analyze_files
      - lint
    if: needs.analyze_files.outputs.xi_web_files == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Install pnpm (version from package.json)
        uses: pnpm/action-setup@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4.3.0
        with:
          node-version-file: package.json
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install turbo
        run: pnpm install -g turbo

      - name: Turbo prune
        run: turbo prune --scope=${{ env.app_name }}

      - name: Install dependencies
        working-directory: ./out
        run: pnpm install

      - name: Build application
        working-directory: ./out
        run: npm run build --filter==${{ env.app_name }}

      - name: Upload build as an artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ env.app_name }}
          path: ./out/apps/${{ env.app_name }}/build

  deploy_xi_web:
    needs:
      - namer
      - build_xi_web
    runs-on: ubuntu-latest
    environment: xi-development

    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ env.app_name }}
          path: out

      - name: Get full folder path for deployment
        id: get_deployment_path
        run: |-
          deployment_path=${{ env.project_name }}/${{ env.app_name }}/${{ needs.namer.outputs.deployment_name }}
          echo "deployment_path=${deployment_path}"
          echo "deployment_path=${deployment_path}" >> $GITHUB_OUTPUT

      - name: Create directory structure to copy
        run: mkdir -p ${{ steps.get_deployment_path.outputs.deployment_path }}

      - name: Create directories on remote
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: --verbose --human-readable --recursive --relative --dirs
          path: ./${{ steps.get_deployment_path.outputs.deployment_path }}
          remote_path: .
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_key_pass: ${{ secrets.SSH_KEY_PASSWORD }}

      - name: Push files to the primary source
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: --verbose --human-readable --compress --recursive --delete
          path: ./out/*
          remote_path: ${{ steps.get_deployment_path.outputs.deployment_path }}/primary
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_key_pass: ${{ secrets.SSH_KEY_PASSWORD }}

      - name: Push files to the secondary source
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: --verbose --human-readable --compress --recursive --delete
          path: ./out/*
          remote_path: ${{ steps.get_deployment_path.outputs.deployment_path }}/secondary
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_key_pass: ${{ secrets.SSH_KEY_PASSWORD }}
